image: registry.gitlab.com/pages/hugo:0.54.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - uname -a
  - sudo apt update
  - sudo apt --yes --force-yes install npm
  - npm install --silent -g postcss-cli

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

