image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - curl https://github.com/gohugoio/hugo/releases/download/v0.55.0/hugo_extended_0.55.0_Linux-64bit.tar.gz > go.tar.gz
  - tar -zxvf go.tar.gz
  - ls

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

