image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - uname -a
  - apt-get update
  - apt-get --yes --force-yes install nodejs
  - apt-get --yes install npm
  - npm install --silent -g postcss-cli

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

