baseURL = "https://wrayfi.github.io/www/"
languageCode = "en-us"
title = "WrayFi"
theme = "hugo-whisper-theme"
relativeurl = true
canonifyURLs = false

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "WrayFi"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Project"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Milestone"
    url = "/milestone/"
    weight = 3

[[menu.main]]
    name = "Final"
    url = "/final/report"
    weight = 4

[params]
  google_analytics_id=""
  homepage_button_link = '/project/'
  homeoage_button_text = 'Project Details'
  homepage_button_link2 = '/milestone/'
  homeoage_button_text2 = 'Milestone'
  homepage_button_link3 = '/final/report'
  homeoage_button_text3 = 'Final Report'
  homepage_intro = "Quetzalli Calderon | Minos Park | Amir Shahatit"
  homepage_image = '/images/router.jpg'

  mainSections = ['project', 'milestone', 'final']

  [params.homepage_meta_tags]
    meta_og_title = "CS 184 Spring 2019 - WrayIFI"
    meta_og_type = "website"
    meta_og_description = "Spring 2019 - Quetzalli Calderon | Minos Park | Amir Shahatit - UC Berkeley"
